# site title
title: bit by bit

# user name or organization name
user: slashbit

# issue repository
repository: blog

# multi-author
authors:

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: 0#d60fcc8be071779685727cd6991aae655599ea9

# posts per page
perpage: 40


# advance config

# organization repository (?)
organization: false

# post order
# order by create time" or "update time"
# 'UPDATED_AT' or 'CREATED_AT'
order: 'CREATED_AT'
